// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace QingStor_SDK_CSharp_Test.TestFeature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("the bucket CORS feature")]
    [NUnit.Framework.CategoryAttribute("bucket_cors")]
    public partial class TheBucketCORSFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "bucket_cors.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "the bucket CORS feature", null, ProgrammingLanguage.CSharp, new string[] {
                        "bucket_cors"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("set the bucket CORS")]
        public virtual void SetTheBucketCORS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("set the bucket CORS", ((string[])(null)));
#line 5
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 6
    testRunner.When("put bucket CORS:", @"{
  ""cors_rules"": [
    {
      ""allowed_origin"": ""http://*.qingcloud.com"",
      ""allowed_methods"": [
        ""PUT"",
        ""GET"",
        ""DELETE"",
        ""POST""
      ],
      ""allowed_headers"": [
        ""X-QS-Date"",
        ""Content-Type"",
        ""Content-MD5"",
        ""Authorization""
      ],
      ""max_age_seconds"": 200,
      ""expose_headers"": [
         ""X-QS-Date""
      ]
    },
    {
      ""allowed_origin"": ""http://*.example.com"",
      ""allowed_methods"": [
        ""PUT"",
        ""GET"",
        ""DELETE"",
        ""POST""
      ],
      ""allowed_headers"": [
        ""*""
      ],
      ""max_age_seconds"": 400
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
    testRunner.Then("put bucket CORS status code is 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("get CORS of the bucket")]
        public virtual void GetCORSOfTheBucket()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("get CORS of the bucket", ((string[])(null)));
#line 48
  this.ScenarioSetup(scenarioInfo);
#line 49
    testRunner.When("get bucket CORS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
    testRunner.Then("get bucket CORS status code is 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
    testRunner.And("get bucket CORS should have allowed origin \"http://*.qingcloud.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("delete CORS of the bucket")]
        public virtual void DeleteCORSOfTheBucket()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("delete CORS of the bucket", ((string[])(null)));
#line 54
  this.ScenarioSetup(scenarioInfo);
#line 55
    testRunner.When("delete bucket CORS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
    testRunner.Then("delete bucket CORS status code is 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
